export enum ConfigType {
  DESK_PHONE = 'DESK_PHONE',
  MAIN_LINE = 'MAIN_LINE',
  START_WORK = 'START_WORK',
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  SERVE_DURATION_GLIP = 'SERVE_DURATION_GLIP',
}
